## 2025-09-24

### Numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.1'

In [ ]:
!pip install numpy

In [ ]:
L = range(1000)
%timeit L2 = [i **2 for i in L]

67.5 μs ± 1.74 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
arr = np.arange(1000)
%timeit arr2 = arr**2

1.78 μs ± 240 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
alist = [1,2,3,4,5,6]

In [ ]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [ ]:
blist = [1,2, None ,4,5,6]

In [ ]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
ar2 = np.array([1.1, 2.2, 3.3])

In [ ]:
print(ar2)

[1.1 2.2 3.3]


In [ ]:
ar2.dtype

dtype('float64')

In [ ]:
list_data = [1, 2. , 3]

ar3 = np.array(list_data, dtype='int')

print(ar3)
print(ar3.dtype)

[1 2 3]
int64


In [ ]:
np.array([1,2, np.nan,4])

array([ 1.,  2., nan,  4.])

In [ ]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [ ]:
(4,)

(4,)

In [ ]:
(1, 4)

In [ ]:
arr2 = np.array([[1,2,3,4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [ ]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [ ]:
arr3 = arr2.reshape(2, -1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [ ]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [ ]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
a = np.array([1,2,3])

a == 2

array([False,  True, False])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

(a == 2) & (b > 10)

array([False,  True, False])

In [ ]:
alist = [[0, 1, 2], [3, 4, 5]]
# 0, 1, 5

In [ ]:
alist[1][2]

5

In [ ]:
alist[0][1]

1

In [ ]:
[[0, 1, 2]
[3, 4, 5]]
# 0, 1 슬라이싱 [0, 1]
# 4, 5 슬라이싱 [4, 5]
# 1, 4를 하나의 리스트에 담아서 보여주세요(슬라이싱?) [1, 4]

In [ ]:
result = [alist[0][1],alist[1][1] ]
result

[1, 4]

In [ ]:
alist[1][1:]

[4, 5]

In [ ]:
alist[0][:2]

[0, 1]

In [ ]:
blist = np.array([[0, 1, 2], [3, 4, 5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
blist[:,1]

array([1, 4])

In [ ]:
print(blist[[0, 1],[1,1] ])

[1 4]


In [ ]:
blist[-1,1: ]

array([4, 5])

In [ ]:
blist[0,:2]

array([0, 1])

In [ ]:
print(blist[0,0], blist[0,1], blist[1,2])

0 1 5


In [ ]:
[start:end:step]
start 포함
end는 미만
step은 기본값 1

In [ ]:
# 슬라이싱 최소 3회 도전해주세요!!!!
[행 , 열 ]

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
clist[: , -2]

array([ 2,  7, 11])

In [ ]:
clist[: , -2: -1]

array([[ 2],
       [ 7],
       [11]])

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = [0, 2, 5]
a[idx]

array([0, 2, 5])

In [ ]:
b = np.array([[1,2,3], [4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
b[[0,1,2],[1, 2, 0]]

array([2, 6, 7])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])

In [ ]:
arr % 2 ==0 

array([False,  True, False,  True, False,  True, False,  True])

In [ ]:
arr[arr % 2 ==0]

array([2, 4, 6, 8])

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([8, 4, 0, 2])
a[idx]

array([99, 55, 11, 33])

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[[2, 0, 1],: ]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
arr100 % 2 != 0

NameError: name 'arr100' is not defined

In [ ]:
import numpy as np

In [ ]:
data = np.array([1, 4, 9, 16])

In [ ]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [ ]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [ ]:
np.sum(data)

np.int64(30)

In [ ]:
np.mean(data)

np.float64(7.5)

In [ ]:
np.std(data)

np.float64(5.678908345800274)

In [ ]:
https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
함수

np.zeros(), np.ones()	모든 요소가 0 또는 1인 배열 생성
np.full()	모든 요소가 특정 값인 배열 생성
np.arange()	간격(step)을 기준으로 연속된 값 생성
np.linspace()	개수(num)를 기준으로 균일한 간격 생성
np.eye()	단위 행렬 생성
np.random.*()	무작위 값을 가진 배열 생성

In [ ]:
유니버설 함수

np.add(x, y)	두 배열의 요소별 덧셈을 수행합니다. (x + y와 동일)
np.subtract(x, y)	뺄셈 (x - y)
np.multiply(x, y)	곱셈 (x * y)
np.divide(x, y)	나눗셈 (x / y)
np.sqrt(x)	각 요소의 제곱근을 계산합니다.
np.exp(x)	지수 함수(ex)를 적용합니다.
np.log(x), np.log10(x)	자연로그(ln), 상용로그(log10)를 계산합니다.
np.sin(x), np.cos(x)	사인, 코사인 등 삼각함수를 적용합니다.
np.maximum(x, y)	두 배열의 같은 위치 요소 중 더 큰 값을 선택합니다.
np.sum(x)	arr.sum() 메소드와 기능적으로 동일합니다.
np.sort(x)	배열을 정렬한 복사본을 반환합니다. (원본 유지)

In [ ]:
메소드

sum()	배열의 모든 요소의 합계를 구합니다. axis로 특정 축 지정 가능.
mean()	배열의 모든 요소의 평균을 구합니다.
std(), var()	표준편차(standard deviation), 분산(variance)을 구합니다.
min(), max()	최솟값, 최댓값을 구합니다.
argmin(), argmax()	최솟값, 최댓값이 있는 곳의 인덱스를 반환합니다.
reshape(shape)	원본 데이터는 유지한 채, 배열의 형태(shape)를 변경합니다.
sort()	배열의 요소를 제자리에서(in-place) 정렬합니다. 원본이 바뀜.
flatten()	배열을 1차원으로 펼칩니다. 복사본을 반환 (원본 유지).
T	배열의 행과 열을 바꾼 전치(Transpose) 배열을 반환합니다.
copy()	배열의 완전한 복사본을 만듭니다. (원본과 독립)

### Pandas

In [ ]:
import pandas

In [ ]:
!pip install pandas


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+13
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [ ]:
pd.options.display.float_format = '{:.0f}'.format

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [ ]:
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [ ]:
df.head()

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [ ]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [ ]:
type(df['국적'])

pandas.core.series.Series

In [ ]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [ ]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [ ]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [ ]:
df.nlargest(7, '키')

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df['이름'][4:]

4       헐크
5     캡틴마블
6    블랙위도우
Name: 이름, dtype: object

In [ ]:
df[3:]

이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
# df.iloc[행번호, 열번호]
df.iloc[:5,:3 ]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [ ]:
df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [ ]:
df.iloc, df.loc

In [ ]:
df.iloc[행번호, 열번호]

In [ ]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [ ]:
df.loc[행이름, 열이름]

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df.loc[3:, '국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [ ]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [ ]:
df.loc[2:5]

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [ ]:
df[df['나이'] > 30]

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
# 나이가 30초과이면서 50미만인 사람들의 전체레코드
df[(df['나이'] > 30) & (df['나이'] < 50) ]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [ ]:
# 키가 180이상인 레코드의 이름과 나이컬럼만 출력
df.loc[df['키'] >= 180, ['이름', '나이', '키'] ]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [ ]:
df['전투력'] = 98

In [ ]:
df['전투력'] = df['전투력'] -5
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [ ]:
df.drop(columns=['전투력'], inplace=True)

In [ ]:
df = df.drop(columns=['전투력'])

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [ ]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [ ]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [ ]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [ ]:
df.dropna()

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df = df.fillna(method='ffill')

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_38928\569672361.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')


In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df.iloc[5, 1] = np.nan
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
# 나이의 평균값으로 결측치를 채워주세요!!!!
df['나이'] = df['나이'].fillna(df['나이'].mean())

In [ ]:
df['나이'].mean()

np.float64(35.5)

In [ ]:
pd.options.display.float_format = None

In [ ]:
df

이름    나이     직업     국적    키            재산
0   아이언맨  58.0    CEO     미국  174  1.150000e+13
1     토르  45.0      신  아스가르드  190  1.150000e+13
2  스파이더맨  18.0   고등학생     미국  177  6.000000e+02
3   원더우먼  27.0     공주  데미스키라  178  6.000000e+02
4     헐크  33.0  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  35.5    파일럿     미국  170  3.400000e+08
6  블랙위도우  32.0    스파이    러시아  170  5.000000e+07

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      float64
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      7 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 468.0+ bytes


In [ ]:
df['재산'].fillna(df['재산'].mean())

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [ ]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
def add_cm(a):
    return  str(a) + 'cm' # 함수를 구현해주세요 174 -> 174cm 로 일괄 변환되도록

def remove_cm(b):
    part = b.replace('cmcm','')
    part_float = float(part)
    return str(part_float) + 'cm'

df['키'] = df['키'].apply(remove_cm)
# df['키'] = df['키'].apply(lambda a: str(a) + 'cm')
df

이름    나이     직업     국적        키            재산
0   아이언맨  58.0    CEO     미국  174.0cm  1.150000e+13
1     토르  45.0      신  아스가르드  190.0cm  1.150000e+13
2  스파이더맨  18.0   고등학생     미국  177.0cm  6.000000e+02
3   원더우먼  27.0     공주  데미스키라  178.0cm  6.000000e+02
4     헐크  33.0  핵물리학자     미국  270.0cm  1.000000e+09
5   캡틴마블  35.5    파일럿     미국  170.0cm  3.400000e+08
6  블랙위도우  32.0    스파이    러시아  170.0cm  5.000000e+07

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      float64
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      object 
 5   재산      7 non-null      float64
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes


In [ ]:
df.groupby('국적')['재산'].mean()

국적
데미스키라    6.000000e+02
러시아      5.000000e+07
미국       2.875335e+12
아스가르드    1.150000e+13
Name: 재산, dtype: float64